services:
  db:
    image: postgres:latest
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  adminer:
    image: adminer:latest
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}
volumes:
  postgres-data:
